// <auto-generated />
using System;
using ClinicGate.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicGate.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicGate.Core.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Forenames");

                    b.Property<string>("GpCode");

                    b.Property<string>("GpInitials");

                    b.Property<string>("GpPhone");

                    b.Property<string>("GpSurname");

                    b.Property<string>("HomeTelephoneNumber");

                    b.Property<string>("NokAddressLine1");

                    b.Property<string>("NokAddressLine2");

                    b.Property<string>("NokAddressLine3");

                    b.Property<string>("NokName");

                    b.Property<string>("NokPostcode");

                    b.Property<int>("NokRelationshipCode");

                    b.Property<string>("PasNumber");

                    b.Property<int>("SexCode");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
